@startmindmap
title GCP menu Security

* Security
**[#White] Security Commander Center
**[#White] reCAPTCHA Enterprise
**[#White] BeyondCorp Enterprise
**[#White] Identity-Aware Proxy
**[#White] Access Context Manager
**[#White] VPC Service Controls
**[#White] Binary Authorization
--[#White] Data Loss Prevention
--[#White] Key Management
--[#White] Certificate Authority Service
--[#White] Secret Manager
--[#White] Access Approval
--[#White] Web Security Scanner
--[#White] Chronicle
--[#White] Managed Microsoft AD

@endmindmap