@startmindmap
title GCP menu IAM & Admin

- **IAM & Admin**
**[#White]  IAM
**[#White]  Identity & Organization
**[#White]  Policy Troubleshooter
**[#White]  Policy Analyzer
**[#White]  Organization Policies
**[#White]  Service Accounts
**[#White]  Workload Identity Federation
**[#White]  Labels
**[#White]  Tags
**[#White]  Settings
**[#White]  Privacy & Security
--[#White]  Identity-Aware Proxy
--[#White]  Roles
--[#White]  Audit Logs
--[#White]  Manage Resources\n(Cloud Resource Manager)
---_ List all projects associated\nwith an account
---_ Create, update, delete, \nundelete, recover projects

--[#White]  Create a project
--[#White]  Asset Inventory
--[#White]  Essential Contacts
--[#White]  Groups
--[#White]  Early Access Center
--[#White]  Quotas

@endmindmap