@startmindmap
title GCP menu BIG DATA

* BIG DATA
**[#White] Composer

-- Dataproc

-- Pub/Sub

-- Dataflow

-- Datastream

**[#White] IoT Core

-- BigQuery

**[#White] Looker

-- Data Catalog 

**[#White] Data Fusion

**[#White] Financial Services

-- Healthcare

-- Life Sciences

**[#White] Dataprep

@endmindmap