@startmindmap
title GCP menu ARTIFICIAL INTELLIGENCE

* ARTIFICIAL \nINTELLIGENCE
**[#White] Vertex AI
***[#Gold] Dashboard
***[#Gold] Datasets
***[#Gold] Features
***[#Gold] Labeling tasks
***[#Gold] Notebooks
***[#Gold] Pipelines
***[#Gold] Training
***[#Gold] Experiments
***[#Gold] Models
***[#Gold] Endpoints
***[#Gold] Batch predictions
***[#Gold] Metadata

--[#White] AI Platform
---[#MistyRose] Dashboard
---[#MistyRose] Data Labeling
---[#MistyRose] Notebooks
---[#MistyRose] Pipelines
---[#MistyRose] Jobs
---[#MistyRose] Models

--[#White] Data Labeling
---[#YellowGreen] Datasets
---[#YellowGreen] Label Sets
---[#YellowGreen] Instructions

--[#White] Document AI
---[#PaleGreen] Overview
---[#PaleGreen] Processors
---[#PaleGreen] Human-in-the-loop AI

**[#White] Natural Language

@endmindmap
