@startmindmap
title GCP menu Security

*[#GreenYellow] Security
** Security Commander Center
** reCAPTCHA Enterprise
** BeyondCorp Enterprise
** Identity-Aware Proxy
** Access Context Manager
** VPC Service Controls
** Binary Authorization
-- Data Loss Prevention
-- Key Management
-- Certificate Authority Service
-- Secret Manager
-- Access Approval
-- Web Security Scanner
-- Chronicle
-- Managed Microsoft AD

@endmindmap