@startmindmap
title GCP menu
* GCP menu
** Home
**[#White] Marketplace
**[#White] Billing
** APIs & Services
** Support
** IAM & Admin
**[#White] Getting started
**[#White] Compliance
** Security
** Anthos
-- Compute
-- Storage
-- Databases
-- Networking
-- Operations
-- Tools
-- Big data
-- Artificial intelligence
-- Other Google solutions
@endmindmap